awslabs/osml-imagery-toolkit

- .github/workflows/python-publish.yml
*Issue #, if available:*
https://github.com/aws-solutions-library-samples/osml-imagery-toolkit/issues/5
*Description of changes:*
Updating package to trigger publishing to PyPi from generic boiler plate action template. There is no way to test this action prior to the file being committed to github due to it needing to exit prior to linking PyPi.
> Creat PyPi publish Github action

- src/aws/osml/gdal/__init__.py
- src/aws/osml/gdal/dynamic_range_adjustment.py
- src/aws/osml/gdal/gdal_utils.py
- src/aws/osml/gdal/typing.py
- src/aws/osml/image_processing/gdal_tile_factory.py
- test/aws/osml/gdal/test_dynamic_range_adjustment.py
- test/aws/osml/image_processing/test_gdal_tile_factory.py
The GDAL tile factory can now automatically rescale pixel values to match a desired output type. This is commonly used when converting panchromatic imagery which often has 11-16 bits per pixel into an 8-bits per pixel representation for visualization. These operations look at the histogram of the input image pixel values and then map them to the output range.
> feat: add optional dynamic pixel range operations to tile factory

- src/aws/osml/formats/sicd/__init__.py
- src/aws/osml/gdal/gdal_dem_tile_factory.py
- src/aws/osml/photogrammetry/__init__.py
- src/aws/osml/photogrammetry/digital_elevation_model.py
- src/aws/osml/photogrammetry/elevation_model.py
- src/aws/osml/photogrammetry/sicd_sensor_model.py
- test/aws/osml/gdal/test_gdal_dem_tile_factory.py
- test/aws/osml/gdal/test_sensor_model_factory.py
- test/aws/osml/photogrammetry/test_digital_elevation_model.py
- test/aws/osml/photogrammetry/test_sicd_sensor_model.py
These changes allow the SICD sensor models to make use of a Digital Elevation Model (DEM) when performing image to world coordinate conversions. These calculations are described in section 10 of the SICD specification. See: https://nsgreg.nga.mil/doc/view?i=5383
In addition to the SICD sensor model updates a new method was added to the elevation model abstraction that allows us to provide summary information about the area around a given world coordinate. This information is currently used by the SICD sensor model to make searching along a terrain surface more efficient but the summary information itself may eventually be useful to other consumers of the abstraction.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> feat: add HAE and DEM projections to SICD sensor model

- .github/workflows/documentation.yaml
**Description of changes:**
- Changed the commands to use `tox -e docs` to generate the docs
- Verified it works using my local github account: https://ranbiraulakh.github.io/osml-imagery-toolkit/index.html
> Fix documentation commands for github actions

- src/aws/osml/photogrammetry/sicd_sensor_model.py
- test/aws/osml/photogrammetry/test_sicd_sensor_model.py
This change fixes an error in the SICD sensor model INCA R/Rdot projection that was uncovered during integration testing. Unit tests have been updated as well to cover this case.
> fix: correct calculation of INCA R/Rdot projection

- src/aws/osml/gdal/dynamic_range_adjustment.py
- src/aws/osml/gdal/gdal_utils.py
This update allows users to create 8-bit per pixel PNG images from SICD images that have floating point complex data. Operations of this type are often used to produce quick visualizations of SAR images.
> feat: update DRA to work with SICDs

- src/aws/osml/gdal/gdal_utils.py
This change enables the RSM sensor models by default for users loading imagery with load_gdal_dataset.
> feat: enable RSM sensor model by default

- src/aws/osml/gdal/gdal_sensor_model_builder.py
- src/aws/osml/gdal/gdal_utils.py
- src/aws/osml/gdal/sensor_model_factory.py
- src/aws/osml/photogrammetry/gdal_sensor_model.py
These changes update the GDAL SensorModel so it works with CRSs other than WGS84.
These updates read the projection well known text from the dataset (if available) and pass it into the sensor model which then uses [PyProj](https://pypi.org/project/pyproj/) for transformations between the image CRS to WGS84 as needed. The toolkit's APIs remain unchanged and WGS84 is still used for all WorldCoordinates but this change will allow the toolkit to work with a wider collection of GeoTIFF images. 
from osgeo import gdal
from aws.osml.gdal import load_gdal_dataset
from aws.osml.photogrammetry import ImageCoordinate
from math import degrees
ds, sm = load_gdal_dataset("./OF6i0_37_000_10836703_20210129_0308R0.tiff")
width = ds.RasterXSize
height = ds.RasterYSize
for test_coordinate in [[0, 0], [0, …
> feat: gdal sensor model now supports non-wgs84 crs

- setup.cfg
- src/aws/osml/image_processing/gdal_tile_factory.py
- src/aws/osml/photogrammetry/gdal_sensor_model.py
- test/aws/osml/photogrammetry/test_gdal_sensor_model.py
This PR includes the following changes:
- Fix a memory leak caused by not deleting the temporary [GDAL vsimem virtual file system](https://gdal.org/user/virtual_file_systems.html#vsimem-in-memory-files) created for each tile by the GDALTileFactory. 
- Fix a bug in the coordinate ordering for GEOGCS coordinate conversions. The original code did not account for the reversal of the (long, lat) coordinate. Using the [always_xy](https://pyproj4.github.io/pyproj/stable/api/transformer.html) flag on the PROJ Transformer will keep everything consistent.
> fix: memory leak and GeoTIFF PROJ errors in v1.1.0

- .github/workflows/documentation-publish.yml
- .github/workflows/osml-imagery-toolkit-build.yml
- .github/workflows/osml-imagery-toolkit-publish.yml
- .github/workflows/python-publish.yml
- .github/workflows/python-tox.yml
**Description of changes:**
- Restructure the workflows. There are 2 workflows:
- osml-imagery-toolkit-build 
- This workflow will be executed only IF the pull request have been made to `dev` or `main` branch. 
- osml-imagery-toolkit-publish
- This workflow will be executed only IF the changes have been merged into `main` branch. It will build and then publish an update to pypi and push documentation pages to `gh-pages` branch
- Eliminate all commits id for github actions and used stable version of it
> Feature/update GitHub actions

- doc/index.rst
- setup.cfg
- src/aws/osml/features/__init__.py
- src/aws/osml/features/feature_index.py
- src/aws/osml/features/imaged_feature_property_accessor.py
- test/aws/osml/features/test_feature_index.py
- test/aws/osml/features/test_imaged_feature_property_accessor.py
This change adds a new aws.osml.features module that will contain classes and functions designed to work with features derived from overhead imagery. As a start two classes have been added:
- **ImagedFeaturePropertyAccessor**: This class abstracts away the different GeoJSON property names various projects have been using (e.g. "bounds_imcoords", "geom_imcoords", "detection.pixelCoordinates", etc.) and provides a consistent interface for reading and writing those properties. This is a first step towards the proposed standard of "imageGeometry" and "imageBBox" properties.
- **STRFeature2DSpatialIndex**: This class is a 2D spatial index of GeoJSON features that will allow us to efficiently find features using spatial queries or nearest neighbor searches. The current implementation is based …
> feat: adds features module with 2D spatial index and basic property utils

- src/aws/osml/photogrammetry/__init__.py
- src/aws/osml/photogrammetry/coordinates.py
- src/aws/osml/photogrammetry/generic_dem_tile_set.py
- test/aws/osml/photogrammetry/test_coordinates.py
- test/aws/osml/photogrammetry/test_generic_dem_tile_set.py
These changes add a flexible directive based custom formatting for GeodeticWorldCoordinates similar to the datetime type. This allows users to easily generate string representations of their coordinates in decimal degrees, decimal radians, as well as combinations of integer degrees, minutes, seconds, hemisphere fields. This formatting also allowed for a more generic DEM tile set implementation where a user can specify a format string to convert a coordinate into a tile ID.
> feat: adds generic DEM tile set and geodetic coordinate formatting

- src/aws/osml/image_processing/gdal_tile_factory.py
- src/aws/osml/image_processing/sicd_updater.py
- src/aws/osml/image_processing/sidd_updater.py
- test/aws/osml/image_processing/test_gdal_tile_factory.py
- test/data/sidd/umbra-sidd200-chip1.ntf
These changes add the ability to create scaled tiles using the GDALTileFactory. A new optional ouput_size parameter has been added to create_encoded_tile() that allows a user to select a desired output size. 
These changes also fix a bug that prevented tiles created from a SIDD image from being output as a SIDD chip. The original code had not been updated to correctly update the SIDD XML metadata and instead was trying to use the SICD updater incorrectly. This PR includes a new SIDD metadata updater and it also updated the original SICD metadata updater to use the xsdata generated constructs instead of direct manipulation of ElementTree.
Unit tests were added to exercise the new scaling function and the broken SIDD chipping (which was missing tests). 
By submitting this pull request, I …
> feat: add ability to create scaled tiles and tiles from SIDD

- .github/workflows/documentation-publish.yml
- .github/workflows/python-publish.yml
Update our GitHub workflows to consistently pin the Python version to 3.10 as part of the setup-python action.
The documentation and publish workflows were updated to be consistent with the tox build which already had the fixed version. This complies with the recommendation on the [setup-python action](https://github.com/marketplace/actions/setup-python):
> The python-version input is optional. If not supplied, the action will try to resolve the version from the default .python-version file. If the .python-version file doesn't exist Python or PyPy version from the PATH will be used. The default version of Python or PyPy in PATH varies between runners and can be changed unexpectedly so we recommend always setting Python version explicitly using the python-version or python-version-file …
> fix: pin python version to 3.10 in github workflow steps

- .github/workflows/osml-imagery-toolkit-build.yml
- .github/workflows/osml-imagery-toolkit-release.yml
- .github/workflows/python-publish.yml
Update the GitHub workflow actions to trigger the documentation build and PyPi publish on a release action. See [GitHub Docs Webhook events & Payloads # Release Publish](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=published#release) for additional details.
> build: publish action now tied to release

- .github/workflows/osml-imagery-toolkit-build.yml
- PACKAGE_DESCRIPTION.md
- setup.cfg
- src/aws/osml/features/__init__.py
This change adds common open source shields to our documentation and moved the python pacakge description to a dedicated PACKAGE_DESCRIPTION.md file. The problem with publishing the README.md directly is that when it is pushed to pypi any relative links become broken. 
> docs: add badges and fix broken links in package description

- .github/workflows/pypi.yml
- .github/workflows/release.yml
In the last (v1.4.0rc1) release the publish to pypi did not execute as expected. It appears to have been skipped because the action has a conditional that only lets it run if the triggering event was a push to origin/main. In this case the triggering event that kicks off the workflow is a published release which wouldn't satisfy the criteria. This change removes the conditional so that the publish to PyPi will occur normally as part of a published release.
> build: update pypi publish to run on release

- src/aws/osml/image_processing/gdal_tile_factory.py
This change corrects a problem that caused the GDALTileFactory to write incorrect XML metadata with SICD tiles. Metadata of that kind is provided to the underlying gdal.translate() function through a dictionary of keyword arguments. Some of those arguments remain the same for an entire image while others vary from tile to tile. When multiple tiles were created from the same image some arguments were carried forward to other chips due to a programming error (a shallow vs. deep copy of an argument that was itself a list of values). As a consequence all tiles after the first one may have incorrect metatada encoded that was leftover from previous tiles. 
Changes have been verified in an integration test environment and are being released ASAP given the severity of the issue. Follow-on PRs …
> fix: incorrect SICD/SIDD metadata added by tile factory

- .coveragerc
- src/aws/osml/image_processing/gdal_tile_factory.py
- test/aws/osml/image_processing/test_gdal_tile_factory.py
- test/data/small.tif
Adding an alpha layer to map tiles to account for cases when the image data does not completely fill the map tile.  Previously these pixels would be filled with black which obstructed the view of lower map layers.
> feat: adding an alpha mask to ortho map tiles for pixels in the tile but outside the image

- src/aws/osml/image_processing/gdal_tile_factory.py
- tox.ini
- This quick fix addresses an issue with the border between the map tiles and out-of-bound pixel coordinates during the remapping process using cv2.remap. When performing image remapping, some coordinates may fall outside the boundaries of the source image. By default, this can result in unwanted black borders if cv2.BORDER_CONSTANT is used, as pixels outside the image bounds are filled with a constant color (typically black). To mitigate this, the code uses `copyMakeBorder` and uses `cv2.BORDER_REPLICATE`, which replicates the edge pixels of the source image around the border. This allows `cv2.remap` to use valid pixel values for out-of-bound coordinates, avoiding the default black borders around the output image. This solution ensures that the edges blend …
> fix: remove border between map tiles

- src/aws/osml/image_processing/gdal_tile_factory.py
- src/aws/osml/image_processing/sar_complex_imageop.py
- test/aws/osml/image_processing/test_gdal_tile_factory.py
This change adds the ability to create map tiles from SAR images with complex pixel values. The changes to the `GDALTileFactory` include updates to convert the 2-band phase/amplitude SICD imagery into an 8-bit per pixel single band imagery meant for human review. This is similar to the dynamic range adjustment normalization applied to electro-optical imagery but it differs in that multiple bands are being combined and normalized to produce a single output image. The calculations in `create_orthophoto_tile` were also updated to provide a better elevation estimations and more consistent mapping of image pyramid level to map tile resolution. These changes will improve the map tiles generated for all sensor types but the effect was particularly noticeable on the test SAR imagery. 
Unit tests …
> feat: add ability to create map tiles from SICD images

- src/aws/osml/image_processing/gdal_tile_factory.py
- test/aws/osml/image_processing/test_gdal_tile_factory.py
The dynamic range adjustment (DRA) calculation wasn't correctly handling imagery with more than 8 bits per pixel per band. The original calculation only computed a histogram of 256 bins and it assumed the binned values were 0-255. This update should make the code work with imagery with a larger dynamic range. 
The automated tests were mocked examples and while they exercised the code they didn't catch this problem. They've been updated to validate the current values but a real test was verified using a representative 3-band (RGB) 12 bit per pixel image. (range adjusted 8-bit PNG tile shown below)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> fix: DRA range calculation for imagery with more than 8 BPP

- src/aws/osml/photogrammetry/sicd_sensor_model.py
This change fixes a bug in the HAERRDotSurfaceProjection code that would sometimes cause a SICD sensor model to fail to geolocate image points using an external DEM model. The code was accidentally using the earth centered fixed (ECF) version of the scene center point (SCP) when computing the ground reference point and adjusting the elevation (z) coordinate like it was a geodetic coordinate. That threw off calculations of the min/max elevation limits for the DEMRRDotSurfaceProjection which eventually led to an exception thrown because the calculations could not be completed ("No solution exists. Distance between ARP and the plane is greater than range."). 
This change updates the calculation to use the geodetic (Lon, Lat, Elevation) version of the SCP. You can see that this change makes …
> fix: bug in HAE RRDot surface projection

- src/aws/osml/photogrammetry/generic_dem_tile_set.py
- test/aws/osml/photogrammetry/test_generic_dem_tile_set.py
This change fixes an error in how the DEM file names are calculated by the GenericDEMTileSet. The original code did not handle coordinates in the South or West hemispheres correctly (negative decimal degrees values). The DEM tile 044W contains elevation values for coordinates [-44.0, -43.0) so a coordinate value of -43.5 needs to be floored to -44. That is the natural behavior of the python floor() operator but the original implementation was relying on the degrees, minutes, seconds calculation in the GeodeticWorldCoordinate format operator which converts the decimal value to a positive number before truncating the degrees. This change floors the number before passing it into the format string ensuring the correct decimal value is chosen for a DEM tile. Unit tests have been updated to …
> fix: generic dem tile names for SW hemisphere

- src/aws/osml/image_processing/__init__.py
- src/aws/osml/photogrammetry/__init__.py
- tox.ini
These changes correct a few small syntax errors noticed in the Sphinx doc generation process. The captions for several figures were not being generated correctly because of indent levels. This change also makes a small update to the DEM example to encourage use of the GenericDEMTileSet instead of the more restrictive version that only works with the USGS commercial SRTM files.
> docs: correct syntax mistakes in features and external type references

- src/aws/osml/photogrammetry/digital_elevation_model.py
- src/aws/osml/photogrammetry/elevation_model.py
- test/aws/osml/photogrammetry/test_digital_elevation_model.py
- test/aws/osml/photogrammetry/test_elevation_model.py
This update adds a boolean return value to the `ElevationModel` `set_elevation` method. This status will be used to support future pull requests.
> feat: add elevation status

- src/aws/osml/photogrammetry/sicd_sensor_model.py
- test/aws/osml/photogrammetry/test_sicd_sensor_model.py
The `SICDSensorModel` requires that an elevation model, if supplied, implement `describe_region` to provide a summary of the area surrounding a point. `ElevationModel` itself indicates an optional return value for this method, though every implemented elevation model in the toolkit provides a summary.
One option is to handle no summary with defaults in the caller, which has been added by this PR. `DEMRRDotSurfaceProjection` has additional initialization parameters for min/max height and spacing. The `SICDSensorModel` will override these will elevation summary information, if available.
Another option is to require implementation of `describe_region` and have every elevation model create defaults. This is the current behavior of the `ConstantElevationModel`.
Defaults were roughly chosen to …
> fix: optional elevation summary in DEM RRDot surface projection

- src/aws/osml/photogrammetry/__init__.py
- test/aws/osml/photogrammetry/test_conditional_elevation_model.py
In an earlier PR I forgot to include the conditional elevation model in the `__init__` import list. It has been added, and the test for it has also been given a more explicit name.
> fix: include conditional model imports
