awslabs/osml-imagery-toolkit

setup.cfg
*Issue #, if available:*
- PyPi website is reporting invalid links
*Description of changes:*
- Update the Project Source URL and Issues URL
=> Update PyPi Links

.github/workflows/documentation.yaml
*Issue #, if available:* N/A
*Description of changes:* Adding a Github workflow for hosting Sphinx documentation on pushes to main. 
=> Sphinx documentation

.github/workflows/documentation.yaml
*Issue #, if available:* N/A
*Description of changes:* Based on security scan findings, I am specifying an exact commit SHA for the `peaceiris/actions-gh-pages` action. 
=> Documentation security improvement

README.md
Updates of the main README.md to include the SICD work and provide a new example of cutting tiles for display.
=> docs: update readme for SAR features

setup.cfg
Update Python library information to use version v1.2.0 in preparation for release.
=> build: update library version to v1.2.0

environment-py311.yml, setup.cfg, tox.ini
*Issue #, if available:*
*Description of changes:*
Updating package dependencies to latest supported versions.
=> fix: bump dependancy versions

src/aws/osml/features/__init__.py, src/aws/osml/features/geolocation.py, src/aws/osml/features/imaged_feature_property_accessor.py, test/aws/osml/features/test_geolocation.py
This change pulls in geolocation utilities currently living in osml-model-runner and updates them to work with any image geometry properties available through the ImagedFeaturePropertyAccessor.
=> feat: add feature geolocation utilities

src/aws/osml/image_processing/gdal_tile_factory.py, src/aws/osml/image_processing/sar_complex_imageop.py, test/aws/osml/gdal/test_dynamic_range_adjustment.py, test/aws/osml/image_processing/test_map_tileset_wmq.py, test/data/sicd/capella-sicd121-chip1.ntf, test/data/sicd/capella-sicd121-chip2.ntf, test/data/sicd/umbra-sicd121-chip1.ntf
These changes correct data validation, numeric overflow, and deprecation warnings that exist in the current code baseline. These changes should not alter the functionality of the software but it eliminates some technical debt in preparation for the next release.
=> fix: resolve unit test warnings

README.md, setup.cfg
These are the build updates necessary to release v1.4.0rc1. The version number for the library has been incremented and small updates to README.md have been made to reflect the new features introduced in earlier PRs.
=> build: bump version to 1.4.0rc1 and update readme

setup.cfg
Update the library version number in preparation for a v1.4.0rc2 release
=> chore: update library version to v1.4.0rc2

setup.cfg
Update the library version to v1.4.0rc3 to so we can release the critical bug fix available in v1.3.2 to our 1.4.0rc baseline.
=> chore: update library version to v1.4.0rc3

src/aws/osml/image_processing/map_tileset_wmq.py
=> docs: fixing typos

src/aws/osml/image_processing/gdal_tile_factory.py, test/aws/osml/image_processing/test_gdal_tile_factory.py
Primary changes:
- Perform DRA using the histogram from the entire image instead of the individual tile.  This prevents a mosaic pattern but may result in areas that are lighter/darker, particularly in large images.
- Image normalization now respects the range_adjustment setting.
- Add MINMAX implementation for range_adjustment.
=> fix: normalize tiles with respect to entire image and use range_adjustment setting

setup.cfg
Update library version to v1.4.0rc4.
=> chore: update library version to v1.4.0rc4

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/pypi.yml, .github/workflows/tox.yml
- Add `workflow_dispatch` to all workflows
=> ci: add workflow_dispatch

setup.cfg
Update the library version to v1.4.0 in preparation for the official release of our map tiling feature.
=> chore: update library version to v1.4.0

setup.cfg
Update library version to v1.4.1 for immediate release of the DRA fix made in PR #61. 
=> chore: update library version to v1.4.1

setup.cfg
Update library version to v1.4.2 for release of the updates driven by testing with additional DEM data sets.
=> chore: update library version to v1.4.2

.github/workflows/slack-notify.yml, .github/workflows/tox.yml, tox.ini
Add automated PR notifications to our team's Slack channel. Also updated automated style checking to only run on files that changed in this commit. 
Tested because you can see the notification for this PR in our Slack channel.
=> chore: add Slack notification for new PRs

.github/copyright.yaml, .github/hooks/check-copyright.py, .pre-commit-config.yaml
Update the copyright check to only check for the presence of a copyright notice using a new custom hook.
=> ci: update copyright hook

environment-py313.yml, setup.cfg, src/aws/osml/image_processing/__init__.py, src/aws/osml/image_processing/sar_complex_imageop.py, test/aws/osml/image_processing/test_sar_complex_imageop.py
•	GDAL: 3.9.2 → 3.11.3
•	PROJ: 9.5.0 → 9.6.2
•	NumPy: <2.3.0 → <2.3.2 (Python 3.12+)
•	GDAL constraint: <3.10 → 3.11.3
⸻
•	Added linear_mapping_complex() to sar_complex_imageop.py
•	Converts SAR complex image pixels to linearly mapped values [0, 1]
•	Supports multiple pixel types:
•	AMP8I_PHS8I
•	RE32F_IM32F
•	RE16I_IM32F
This resolves a unit test failure that emerged after dependency updates:
```
E       AssertionError: np.complex64(0.14314882+0.35022455j) not less than or equal to 0.02
```
⸻
The linear_mapping function should:
•	Accept SAR magnitude values as input
•	Apply min-max normalization → output range [0, 1]
•	Return real numbers, not complex
•	Function returned complex numbers, causing test failures.
•	Input file (capella-sicd121-chip2.ntf) …
=> feat: update core dependancies

src/aws/osml/photogrammetry/digital_elevation_model.py, test/aws/osml/photogrammetry/test_digital_elevation_model.py
An additional `propagate_nans` argument has been added to the constructor of `DigitalElevationModel`. When set to True, the default `RectBivariateSpline` interpolator is replaced with a more general `RegularGridInterpolator` that ignores missing data values. This change prevents large negative no-data values from being utilized as input to fit the interpolation grid.
We have not verified whether the interpolation grid interprets the origin as the center of the pixel or the upper left corner of the pixel. Additional testing may be required to ensure that we do not need to add an additional coordinate offset.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> fix: handle missing values in tiles
